import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useSession, signIn, signOut } from "next-auth/react"
import Link from 'next/link'
import HeroSVG from "../assests/hero.svg"
import AutomationSVG from "../assests/automation.svg"
import axios from 'axios'
// import { ReactComponent as HeroSVG } from "../assests/hero.svg"
const Home: NextPage = () => {
  const { data: session } = useSession()
  console.log("🚀 ~ session:", session)

  const subscribeToEmails = async () => {
    try {
      const response = await axios.get("/api/auth/subscribe");
      const { success } = response.data;
      if (success) {
        console.log("🚀 ~ subscribeToEmails ~ success:", success)
      }
    } catch (err) {
      console.log("🚀 ~ subscribeToEmails ~ err:", err)
    }
  }

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Create navbar */}
      <nav className='h-[16vh]'>
        <header className="text-gray-600 body-font">
          <div className="container mx-auto flex flex-wrap p-5 flex-col sm:flex-row items-center">
            <a className="flex title-font font-medium items-center text-gray-900 mb-4 md:mb-0">
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" stroke="currentColor" strokeLinecap="round" stroke-linejoin="round" stroke-width="2" className="w-10 h-10 text-white p-2 bg-indigo-500 rounded-full" viewBox="0 0 24 24">
                <path d="M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5"></path>
              </svg>
              <span className="ml-3 text-xl">Email AutoSender</span>
            </a>
            <nav className="sm:ml-auto flex flex-wrap items-center text-base justify-center">
              <a className="mr-5 hover:text-gray-900">About</a>
            </nav>
            {
              session && session.user ? (
                <button onClick={() => signOut()} className="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base mt-4 sm:mt-0">Sign out
                </button>
              ) : (
                <button onClick={() => signIn()} className="inline-flex items-center bg-gray-100 border-0 py-1 px-3 focus:outline-none hover:bg-gray-200 rounded text-base sm:mt-0">Sign in
                  <svg fill="none" stroke="currentColor" strokeLinecap="round" stroke-linejoin="round" stroke-width="2" className="w-4 h-4 ml-1" viewBox="0 0 24 24">
                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                  </svg>
                </button>
              )
            }

          </div>
        </header>
      </nav>
      <main className=' flex items-center justify-center' >

        {/* create book card */}
        {session && session.user ? (

          <>
            <section className="text-gray-600 body-font">
              <div className="container px-5 mx-auto flex flex-wrap items-center justify-center">
                <div className="flex flex-wrap w-full">
                  <div className="lg:w-2/5 md:w-1/2 md:pr-10 md:py-6 ">
                    <div className="flex relative pb-12">
                      <div className="h-full w-10 absolute inset-0 flex items-center justify-center">
                        <div className="h-full w-1 bg-gray-200 pointer-events-none"></div>
                      </div>
                      <div className="flex-shrink-0 w-10 h-10 rounded-full bg-indigo-500 inline-flex items-center justify-center text-white relative z-10">
                        <svg fill="none" stroke="currentColor" strokeLinecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
                          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                        </svg>
                      </div>
                      <div className="flex-grow pl-4">
                        <h2 className="font-medium title-font text-sm text-gray-900 mb-1 tracking-wider">STEP 1</h2>
                        <p className="leading-relaxed">Authorize us to send email on behalf of you as you have already give permission by Signing with Google </p>
                      </div>
                    </div>
                    <div className="flex relative">
                      <div className="flex-shrink-0 w-10 h-10 rounded-full bg-indigo-500 inline-flex items-center justify-center text-white relative z-10">
                        <svg fill="none" stroke="currentColor" strokeLinecap="round" stroke-linejoin="round" stroke-width="2" className="w-5 h-5" viewBox="0 0 24 24">
                          <path d="M22 11.08V12a10 10 0 11-5.93-9.14"></path>
                          <path d="M22 4L12 14.01l-3-3"></path>
                        </svg>
                      </div>
                      <div className="flex-grow pl-4">
                        <h2 className="font-medium title-font text-sm text-gray-900 mb-1 tracking-wider">FINISH</h2>
                        <p className="leading-relaxed">Subscribe to the service by clicking here </p>
                        <button onClick={() => { subscribeToEmails() }} className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Subscribe</button>
                      </div>
                    </div>
                  </div>
                  {/* <div className="lg:w-3/5 md:w-1/2  flex items-center justify-center "> */}
                  <Image src={AutomationSVG} className="object-cover object-center rounded-lg md:mt-0 mt-12" alt="step" />
                  {/* </div> */}
                </div>
              </div>
            </section>
          </>
        ) : (
          <div className='h-[84vh]'>
            {/* <p>You need to sign in to access the books</p>
              <h1 className="text-3xl font-bold underline">
                Hello world!
              </h1> */}
            <section className="text-gray-600 body-font">
              <div className="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
                <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
                  <h1 className="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Automate your Email
                    <br className="hidden lg:inline-block" />&nbsp;Let people know you are on Vacation
                  </h1>
                  <p className="mb-8 leading-relaxed">Send Automated Email to your colleagues to let them know are busy with important work</p>
                  <div className="flex justify-center">
                    <button onClick={() => signIn()} className="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">Let's Start Automation</button>
                  </div>
                </div>
                <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
                  {/* <HeroSVG /> */}
                  <Image className="object-cover object-center rounded" alt="hero" src={HeroSVG} />
                </div>
              </div>
            </section>
          </div>
        )}
      </main>
    </div>
  )
}

export default Home
